version: "3.7"

services:
    express-server:
        build:
            context: .
            dockerfile: ./Dockerfile.dev
        depends_on:
            - postgres
        ports:
            - "3000:3000"
            - "5000:5000"

    postgres:
        image: postgres:11
        ports:
            - "35432:5432"
        environment:
            POSTGRES_USER: user
            POSTGRES_PASSWORD: password
            POSTGRES_DB: db
